### ISSUE TITLE
Files without license information

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#104]
While updating the license information in Frontend, I noticed that some files in Backend didn't contain license information. I'm not sure that all of these files need to, but I thought I'd mention them.

The following files don't contain license information in Backend but do in Frontend, though I'm not sure it's needed:

* `test/`
* `.gitignore`
* `*.md`
* `.eslintrc.json`. Adding comments results in an error for some `.json` files (for example, `package.json`), but for other files, adding comments does not result in an error.

These files don't have an equivalent in Frontend, but I thought I'd mention them as well:

* `config/default.json`
* `.circleci/config.yml`
*  `Makefile`

**Comment by clint-tseng** [comment]
I looked and it's only recommended and not required that such files have license information. I think this makes sense, as they're not really part of a distribution.

**Comment by matthew-white** [comment]
That makes sense to me, and I don't have a strong preference one way or the other. CC @lognaturel in case she has thoughts.

**Comment by lognaturel** [comment]
Yeah, I wouldn't put a header on those.

**Comment by matthew-white** [comment]
Sounds good, I can start leaving the header off those files in Frontend as well. (Maybe I'll remove the header from existing files like that at some point as well...)
