### ISSUE TITLE
Integrate with Enketo

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/central-backend#109]
I'd like to gauge interest in the following 3 types of additional functionality (fund-raising related). They should probably be split into 3 different issues (but I wasn't completely sure if this is the right repo to post backend-frontend-combo issues, or if it should go to the forum first).

### Viewing/pre-viewing/pdf-ing empty forms or records loaded into a form:
* form preview (as on xlsform.opendatakit.org): https://apidocs.enketo.org/v2#/post-survey-preview
* empty form, as pdf: https://apidocs.enketo.org/v2#/post-survey-view-pdf
* record in form, as pdf: https://apidocs.enketo.org/v2#/post-instance-view-pdf
* record in form, readonly viewing: https://apidocs.enketo.org/v2#/post-instance-view

### Editing already submitted data in a browser (as used in Ona, KoBo)
* https://apidocs.enketo.org/v2#/post-instance (requires instanceID -> deprecatedID swap)

### Collecting data in a browser
* online-only, single-submission (like SurveyMonkey): https://apidocs.enketo.org/v2#/post-survey-single-once
* online-only, multi-submission: https://apidocs.enketo.org/v2#/post-survey
* offline-capable, multi-submission: https://apidocs.enketo.org/v2#/post-survey-offline

**Comment by yanokwa** [comment]
For issues that touch both the backend and frontend, file the issue at https://github.com/opendatakit/central.

Regardless, I think this issue might be best as a feature request at https://forum.opendatakit.org/c/features since probably requires some user input and it's not easy to close as done.

**Comment by MartijnR** [comment]
Thanks. I'll post it in the forum.
