### ISSUE TITLE
OData: renamespace system metadata out of .user

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#110]
Right now we generate a `__system` complex type and namespace it alongside all the other user-defined complex types (groups). This puts it at eg `org.opendatakit.user.formname.__system`. Instead, we could place it at `org.opendatakit.submission.metadata`, for instance. But this is not actually trivial to do and verify, so I'm punting on it for now.

**Comment by clint-tseng** [comment]
(and this is puntable because it's not really a user-facing change; the data structure will remain identical)
