### ISSUE TITLE
Validate xmlFormId

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#119]
On Frontend, I make some assumptions about `xmlFormId`, and I use it in a lot of places without URL-encoding it. Do we validate `xmlFormId` in Backend? If not, how about we validate that it is a single URL-friendly word? I don't see much in the ODK XForms spec about constraints for the form ID. However, I think Aggregate imposes some constraints — maybe that the form ID is a valid database table name? I think being able to make some assumptions in Frontend helps improve the clarity of that code.

**Comment by clint-tseng** [comment]
there's nothing in the spec, so i'm uncomfortable enforcing anything here. there are probably spots in the backend that would cause problems here too, but we'll just have to deal with it i think.

**Comment by matthew-white** [comment]
Sounds good. I've created an issue in the Frontend repo and will try to make sure that `xmlFormId` is encoded everything there.

**Comment by clint-tseng** [comment]
i think given the conclusion here this ticket itself is a noop. if we discover that the xmlFormId as-is does cause problems, we will revisit. but right now i'm thinking and i can't really imagine what that would be.

**Comment by matthew-white** [comment]
I had one thought come to mind, how about `<downloadUrl>` and `<manifestUrl>` in `openrosa.js`? Do we need to encode the `xmlFormId` for those?

**Comment by clint-tseng** [comment]
already done; those use `{{xmlFormId}}` which handles all that

**Comment by matthew-white** [comment]
`{{xmlFormId}}` is for HTML-escaping, right? Are there cases where a character is safe for HTML but would still need to be encoded for a URL? (Maybe a space is an example of that?)

**Comment by clint-tseng** [comment]
oh. i'm.. not extraordinarily concerned, to be honest.
