### ISSUE TITLE
Include app user display name in CSV export

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#132]
A [post in the Forum](https://forum.opendatakit.org/t/odk-central-app-username-on-the-csv/15433) mentions that the app user display name appears in the Frontend submissions table but not the exported CSV file. @clint-tseng, what do you think about adding this to the CSV file? I could see how it could be useful to have that data in the CSV.

Also, I know we include the app user display name in the OData under the `__system` property, but I was wondering whether you would consider that part of the official Central API.

**Comment by clint-tseng** [comment]
@matthew-white @ggalmazor does Aggregate do something like this? is there something else Aggregate does that's similar that we can copy.

**Comment by matthew-white** [comment]
I'm pretty sure that Briefcase doesn't include this information upon export. I'm not sure about Aggregate...

**Comment by clint-tseng** [comment]
okay. i'll try to do something vaguely intelligent, then. thanks!

**Comment by clint-tseng** [comment]
the talk about people depending on briefcase output makes me wary of adding a column that isn't there in briefcase..

**Comment by clint-tseng** [comment]
maybe i'll add it at the very very end

**Comment by clint-tseng** [comment]
@yanokwa i implemented this but want a gut check on deviating from briefcase (given i just tried so hard to exactly match it)
