### ISSUE TITLE
CSV filenames: use unqualified repeat group names

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#145]
Right now for a CSV export, the name of a repeat group CSV file contains the repeat group's fully qualified name. For example, if a non-repeat group named `group1` contains a repeat group named `repeat1`, and `repeat1` contains a repeat group named `repeat2`, then the name of the CSV file for `repeat2` will be `[form ID]-group1-repeat1-repeat2.csv`.

Instead of using the repeat group's fully qualified name, we could use its unqualified name. That would mean that the CSV file for `repeat2` would be named `[form ID]-repeat2.csv`.

One advantage of this is that there is a [Windows limit](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation) such that file paths (not just file basenames) cannot exceed 260 characters, and unqualified names should be less likely to run into this limit.

XLSForms do not allow two different repeat groups to have the same name, but the XForms spec does. That means that we'd have to implement a disambiguation strategy so that the filenames for two such repeat groups are different.

CC @ggalmazor, as there's been discussion around using unqualified names in Briefcase as well.

**Comment by clint-tseng** [comment]
yeah.. @ggalmazor have you decided how to do this just yet? on the Central side it's all async so it's tough to coördinate deduplication but if you share your strategy i'll do my best to replicate it.

**Comment by ggalmazor** [comment]
Hi, @matthew-white, @clint-tseng!

I haven't really thought anything about this yet, but I guess now is as good a moment as any! :)

- Briefcase compiles the list of files it's going to write before starting to process submissions
  - Once Briefcase has parsed the blank form with JR and it has a `Model` with the instance's structure and other metadata, I ask for the list of fields (Model instances as well) that are repeatable:

    ```java
    List<Model> getRepeatableFields() {
      return flatten()
          .filter(field -> field.model.getDataType() == DATATYPE_NULL && field.model.isRepeatable())
          .collect(toList());
    }
    ```
    
    - I guess that traversal order while flattening the model is key if we want Briefcase and Central to produce the same files. Briefcase goes sequentially through the fields in the same order they're defined in the XML file.
	- JR gives me a `TreeElement.isRepeatable()` method to query that and I also verify the field's type, which should be `null` for groups, just in case.

  - Since further processing will/should occur in parallel, I have to sort out any deduplication at this moment
    - I can group files per field name, which will get me a `Map<String, List<Model>>` and:
      - If there's only one element in the list, ignore it
      - If there's more than one element in the list, give it a sequence number, so that the output filename follows the `FORM_NAME-REPEAT-NAME-NUMBER.csv` pattern.

Does that sound reasonable?

**Comment by matthew-white** [comment]
`FORM_NAME-REPEAT-NAME-NUMBER.csv` sounds good to me.

For the `NUMBER` suffix, what do you think about preceding that with a character that is not used in XML names? For example, maybe we could use `=` instead of `-`? This might be a little far-fetched, but in theory, if the character can be used in XML names, a duplicate repeat group name + numeric suffix could conflict with another repeat group's name. For example, you could have a form with these three repeat groups: `repeat`, `repeat` (duplicate name), and `repeat-1` (which would result in a filename conflict). Using something like `=` seems a little funny, but I also think that duplicate repeat group names should be rare, so it's not something that most users would encounter.

Also, out of curiosity, does Briefcase currently use the form ID or the form title/name for filenames?

**Comment by ggalmazor** [comment]
> Using a different char to separate the repeat name from the sequence number

I don't have a strong opinion on this one. If `=` feels right, let's do it ;)

> Also, out of curiosity, does Briefcase currently use the form ID or the form title/name for filenames?

Briefcase uses the form's title/name.

**Comment by matthew-white** [comment]
> > Using a different char to separate the repeat name from the sequence number
> 
> I don't have a strong opinion on this one. If `=` feels right, let's do it ;)

This sounds good to me! :+1:

@clint-tseng, how does @ggalmazor's strategy sound to you? How possible would it be to implement it in Central? Also, what do you think about using the form name instead of the form ID for the filename?

**Comment by clint-tseng** [comment]
sounds reasonable overall. some questions:

1. what's the filename sanitization strategy on your end?
2. can we use `~` instead of `=`?
3. does the number get written unconditionally? if so is it depth first or breadth first?

**Comment by matthew-white** [comment]
>     2. can we use `~` instead of `=`?

Sounds good to me!

**Comment by ggalmazor** [comment]
> what's the filename sanitization strategy on your end? 

I'll check the code and get back to you on this one

> can we use ~ instead of =?

Why not? It even has a fun name in Spanish "virgulilla" :)

> does the number get written unconditionally? if so is it depth first or breadth first?

I'd swear it's depth-first, but let me check it with the code just in case parallelization plays a role here.

In any case, I'm thinking about *not* adding the suffix if there are no duplicates. It feels less confusing for users but I don't have a strong opinion on that.

**Comment by matthew-white** [comment]
> In any case, I'm thinking about *not* adding the suffix if there are no duplicates. It feels less confusing for users but I don't have a strong opinion on that.

This makes sense to me too. I think in the vast majority of cases, there won't be duplicate repeat group names, so I think it makes sense to leave off the suffix for repeat groups with unique names.

**Comment by clint-tseng** [comment]
@ggalmazor very well, then—more cases for you, more cases for me :)

**Comment by ggalmazor** [comment]
This is what we're doing with filenames:
```java
text.replaceAll("\\p{Punct}", "_").replaceAll("\\p{Space}", " ")
```
If I interpret this regexp correctly, we change all punctuation chars to the underscore char and we normalize any white space to the " " white space ¯\\_(ツ)_/¯

**Comment by clint-tseng** [comment]
Hmm, right now we are using [this one](https://www.npmjs.com/package/sanitize-filename) which i guess is more lenient. Should I switch to yours or vice versa?

**Comment by ggalmazor** [comment]
I trust better yours. It looks like better tested and documented. I'll see how I can bring that into Briefcase.

**Comment by ggalmazor** [comment]
How does https://www.npmjs.com/package/sanitize-filename deal with UTF-8 filenames that use non-alphanumeric character systems?

**Comment by clint-tseng** [comment]
it seems like it doesn’t; should it? maybe it’s not a bad idea to go with
the more destructive superset?

**Comment by ggalmazor** [comment]
Briefcase supports non-alphanumeric filenames. Stuff like `უნივერსიტეტის გამოკითხვა-with_respondent-selection_table.csv` is perfectly fine.

**Comment by ggalmazor** [comment]
I've pushed https://github.com/opendatakit/briefcase/pull/673 to begin comparing both strategies. Some thoughts about this:
- Briefcase feels too restrictive with punctuation characters
- Central deals with Windowsy COM, LPT, and friends, although we could argue that this is more important in Briefcase than in Central
- Central cleans heading and trailing spaces and dots, which is nice.
- Both deal correctly with non-visible, whitespacey characters, although `\p{Punct}` seems nicer
- Both support UTF-8 non-alphanumeric characters, which is nice.

Some of the sanitizing cases in Central's library feel somewhat arbitrary, but I wouldn't worry much about it anyway.

**Comment by ggalmazor** [comment]
Wow, a month has gone by already! :)

I've compiled a list of input strings to use it as a baseline and I've written a Mocha test to get the expected outputs and use them for the implementation in Briefcase. Here's the gist: https://gist.github.com/ggalmazor/2994d434eb16cdfd658e1260fe357885#file-central-sanitizing-use-cases-js

PR https://github.com/opendatakit/briefcase/pull/673 has an equivalent test with the same use cases.

Do you think it could be useful to include the test from linked gist into Central's test suite?

**Comment by clint-tseng** [comment]
as in, copy those cases directly into the tests? if so, yeah totally.

**Comment by ggalmazor** [comment]
OK, I'll create a PR with those :)

**Comment by clint-tseng** [comment]
no need; i imported them from the gist. i marked you as author so if they explode i don't get blamed. :)

**Comment by ggalmazor** [comment]
Thanks, Clint! I was having trouble finding time for this :)
