### ISSUE TITLE
Pick up and save deviceIds on form submission

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/central-backend#150]

**Comment by alexpatow** [comment]
@clint-tseng as mentioned in slack, I'll take a look at this

**Comment by alexpatow** [comment]
@clint-tseng 

Is this the endpoint which needs to grab the deviceId: [https://odkcentral.docs.apiary.io/#reference/openrosa-endpoints/openrosa-form-submission-api/openrosa-form-submission-api](https://odkcentral.docs.apiary.io/#reference/openrosa-endpoints/openrosa-form-submission-api/openrosa-form-submission-api)? 

It looks like the deviceId is part of the query string in the POST request (taken from the Collect app logs):

```
I/HttpClientConnection: Issuing POST request to: https://opendatakit.appspot.com/submission?deviceID=imei%3A358240051111110
```

Please let me know if this approach sounds good:
- new migration to create deviceId column in submissions table
- get deviceId from req.query.deviceID in `resources/submissions`
- extend the `PartialSubmission.complete` method in `model/instance/submission` to accept deviceId as a parameter
- change `.orElseGet(() => partial.complete(form, auth.actor()).create()))` in `resources/submissions` to `.orElseGet(() => partial.complete(form, deviceId, auth.actor()).create()))`
- add deviceID query string to integration tests

Questions: 
- do we need to do any formatting on the deviceID in the query string (looks like it comes in as encoded "imei:<id>")?
- How do these lines work, will I need to add deviceId to them?
```
  all: [ 'id', 'formId', 'instanceId', 'xml', 'submitter', 'createdAt', 'updatedAt', 'deletedAt' ],
  readable: [ 'instanceId', 'submitter', 'createdAt', 'updatedAt' ]
```

Thanks,

Alex

**Comment by clint-tseng** [comment]
hey alex! CIL

> Is this the endpoint which needs to grab the deviceId: https://odkcentral.docs.apiary.io/#reference/openrosa-endpoints/openrosa-form-submission-api/openrosa-form-submission-api?

yeah, that's the one.

> It looks like the deviceId is part of the query string in the POST request (taken from the Collect app logs):
> 
> ```
> I/HttpClientConnection: Issuing POST request to: https://opendatakit.appspot.com/submission?deviceID=imei%3A358240051111110
> ```

great, this was what i sort of remembered from past discussion but i wasn't sure about the details. that seems right to me. i wouldn't count on it always being present, though.

> Please let me know if this approach sounds good:
> 
> * new migration to create deviceId column in submissions table
> * get deviceId from req.query.deviceID in `resources/submissions`
> * extend the `PartialSubmission.complete` method in `model/instance/submission` to accept deviceId as a parameter
> * change `.orElseGet(() => partial.complete(form, auth.actor()).create()))` in `resources/submissions` to `.orElseGet(() => partial.complete(form, deviceId, auth.actor()).create()))`
> * add deviceID query string to integration tests

yes. i think that all sounds great. for the `.complete()` param order i would prefer `form, auth.actor(), deviceId` since `deviceId` is the most optional of the lot. and for the integration tests, be sure to test with and without.

> * do we need to do any formatting on the deviceID in the query string (looks like it comes in as encoded "imei:")?

i think i would just leave it exactly as-is. the only processing i would consider (but i don't really think is necessary) is perhaps crushing `''` to `null` (there might even be a util function for that already).

> * How do these lines work, will I need to add deviceId to them?
> 
> ```
>   all: [ 'id', 'formId', 'instanceId', 'xml', 'submitter', 'createdAt', 'updatedAt', 'deletedAt' ],
>   readable: [ 'instanceId', 'submitter', 'createdAt', 'updatedAt' ]
> ```

the short answer is: yes, add it to them both. the long answer is: `all` is generally used when selecting fields out of the database for a join operation, so the db query layer knows how to sort apart the postgres projection tuple into actual structured objects once the data returns. `readable` indicates which fields will be outputted for API responses when `.forApi()` is called (this is typically done automatically by the framework).

**Comment by clint-tseng** [comment]
(oh, and i think there is an `ExtendedSubmission` in that same file so you'll want to add `deviceId` to `all` and `readable` for that too.)

**Comment by alexpatow** [comment]
Awesome, thank you!

**Comment by clint-tseng** [comment]
done via #175
