### ISSUE TITLE
Semantic issues with API documentation

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/central-backend#153]
According to the editor on Apiary, we have two semantic issues with our docs.

1264: ignoring unrecognized block
> These are in alphabetic order, with the exception that the `Extended` versions of each structure, where applicable, is listed immediately following the standard version.

1318: no value(s) specified
> + type: (Form Attachment Type, required) - The expected type of file as specified in the XForm.

**Comment by clint-tseng** [comment]
yeah. both of these i’ve known for a while. in both cases i feel having the
warning is better than the alternative.

**Comment by clint-tseng** [comment]
yeah, they don't have any concept of a comment, since theoretically everything is just visible.
