### ISSUE TITLE
Form Attachments are Actees but Submission Attachments are not

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#173]
For now, this is inconsequential because all permissions are gated by Project.

One might imagine that the easiest answer is to strip Actee off of FAs, but on the other hand, it makes audit logging easier/more direct to have some direct identifier rather than go through auxiliary data in the JSON.

Perhaps the real problem is that Audit logging should not be based on Actees. It depends on which Audit questions we want to answer.

**Comment by clint-tseng** [comment]
looking this over again now i think the correct answer is to make SAs into Actees. will likely do this for 0.6.

**Comment by issa-tseng** [comment]
okay i decided that actually it's just too much overhead to create actees for submissions+submission attachments on intake, for very little gain. i'd rather have the performance penalty on audit log retrieval than on submission creation. so we're going to de-actee form attachments.
