### ISSUE TITLE
NPE on error handling if user agent header does not exist

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#201]
as seen here:
https://sentry.io/organizations/opendatakit/issues/1039160706/?project=1298632

relating to this line:
https://github.com/opendatakit/central-backend/blob/master/lib/http/endpoint.js#L182

**Comment by NizamLZ** [comment]
@opendatakit-bot claim

**Comment by NizamLZ** [comment]
@opendatakit-bot claim --force
