### ISSUE TITLE
sanitize password change requests on sentry

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#211]

**Comment by NizamLZ** [comment]
I would be happy to work on it, can you suggest a starting point? I don't understand much just by the title of the issue.

**Comment by issa-tseng** [comment]
yes, sorry!

when a user tries to [set their password for the first time](https://github.com/opendatakit/central-backend/blob/master/lib/resources/users.js#L57) or [change their password](https://github.com/opendatakit/central-backend/blob/master/lib/resources/users.js#L104) their password input is sent as plaintext as part of the `POST` body.

my understanding from the documentation (and from similar services i've used in the past) was that the input would automatically be sanitized and not sent to sentry if the term password was involved with the request (though now looking at it even if this were true the initial password set _doesn't_ so i messed up either way).

the goal here is for these two requests to never send the payload data to sentry.

**Comment by NizamLZ** [comment]
@opendatakit-bot claim
