### ISSUE TITLE
Upgrade Sentry

### ISSUE THREAD

**Issue by florianm** [opendatakit/central-backend#216]
Probably totally minor: Sentry says `We recommend you update your SDK from version 4.1.1 to version 5.4.3`.
Could https://github.com/opendatakit/central-backend/blob/master/package.json#L33 then
read `"@sentry/node": "~5",`?

**Comment by NizamLZ** [comment]
@opendatakit-bot claim

**Comment by issa-tseng** [comment]
thank you @NizamLZ !!
