### ISSUE TITLE
Tests fail in master

### ISSUE THREAD

**Issue by NizamLZ** [opendatakit/central-backend#220]
![odk-backend-build-error](https://user-images.githubusercontent.com/9017268/61381100-2a699980-a8c8-11e9-9782-dc8660b6db9a.gif)

**Comment by NizamLZ** [comment]
I am also getting this:
![image](https://user-images.githubusercontent.com/9017268/61381358-96e49880-a8c8-11e9-8a81-698b383eef92.png)

**Comment by issa-tseng** [comment]
hm. they work on my machine, and they work on circleci. does it work if you do just `make test` rather than `make test-full`? are you on node 12+?

**Comment by akshay-ap** [comment]
@NizamLZ I think this might help you out: #181

**Comment by issa-tseng** [comment]
except that i know his tests have worked before, so it's probably something i introduced with the encryption branch merge, which included changes to the test setup script and an upgrade to node 12+.

**Comment by NizamLZ** [comment]
Node 12! Ohh ok. I was on node 8 as before. Didn't realize. I am sure it will work with node 12. I was also wondering how did it work on circleci and not on my machine!!

**Comment by issa-tseng** [comment]
:) here's hoping!
