### ISSUE TITLE
Uploading XML media attachment results in "invalid error"

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/central-backend#243]
Using [external-xml.zip](https://github.com/opendatakit/central-backend/files/3962979/external-xml.zip) and frontend:
1. Upload the form
1. Attempt to upload the XML media attachment

A red banner with "Something went wrong: the server returned an invalid error." The upload appears to succeed but the file is empty.

versions:
75f11f18b6d697a73b025b46a9d0e7f6e2e5f0c0
U0000000000000000000000000000000000000000 client
+63ecaece46a52fd0e8cf4a0f64b2d189660e149b server (v0.6.0-beta.0-54-g63ecaec)

**Comment by issa-tseng** [comment]
0.6? why not 0.7?

**Comment by lognaturel** [comment]
I was using antinodes for trying something with Collect. Is it easy for you to try to repro on a more recent environment? It's not urgent, this is not a very widely used feature.

Note that I also uploaded other forms with other media types at that same time so that's why I suspect it's related to the media type but I suppose it could be something else.
