### ISSUE TITLE
Have submissions .csv output match Briefcase

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-backend#42]
When Jubilant outputs multiple .csv files, how closely should their format match Briefcase? I tend to think that they should match as closely as possible so that extensions and workflows based on the Briefcase output will continue to work with Jubilant. How much work would that entail?

**Comment by lognaturel** [comment]
Seems there wouldn't be that many decision points that would lead to differences. What kinds of differences have you seen/are you anticipating?

**Comment by matthew-white** [comment]
I think we should do a closer look at some point, but the only difference I've seen so far has to do with IDs/keys. In Briefcase, the main .csv file has `meta-instanceID` and `KEY` columns. Each repeat group .csv file has a `PARENT_KEY`, a `KEY`, and a `SET-OF-*` column. In repeat group .csv files,  `KEY` seems to uniquely identify rows, but I'm less sure what the `SET-OF-*` columns are for.

I would hope not, but maybe for some workflows, the column order of the IDs would matter.

Does Briefcase output `date`, `time`, `select_multiple`, and `geopoint` fields exactly as Aggregate receives them? Or does it do additional formatting?
