### ISSUE TITLE
Reap expired sessions

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-backend#63]

**Comment by florianm** [comment]
I can't login after a service container restart (nginx and db untouched, just restarted service to use own sentry logging config - nothing sent yet  but that's another story for another ticket to annoy @issa-tseng ;-) ). I see an XHR request to `https://odkcentral.MYDOMAIN/v1/sessions/restore` timing out. Could this be related? How can I kill old sessions?

**Comment by issa-tseng** [comment]
i think it's extremely unlikely this ticket is related to your issue. sounds like you got it worked out.
